{{- $servicePrefix:= printf "%s" .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $servicePrefix }}-configmap
data:
  {{- with .Values.config }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  TZ: "Asia/Dhaka"
  SERVER_PORT: "{{ .Values.service.targetPort }}"
  SPRING_PROFILES_ACTIVE: "k8s"