{{- $servicePrefix:= printf "%s" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $servicePrefix }}
{{- if .Values.service.labels }}
  labels:
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.kind "StatefulSet" }}
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
{{- end }}
  selector:
    app: {{ $servicePrefix }}-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
